### ISSUE TITLE
[Feature Request] Set reviewers field along with assignees

### ISSUE THREAD

**Issue by nodaguti** [cats-oss/github-action-auto-assign#207]
As you may know [GitHub's scheduled reminders feature](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-your-membership-in-organizations/managing-your-scheduled-reminders) enables you to receive a list of pull requests assigned to you at a regular basis.

<img width="437" alt="Dashboard for Scheduled Reminders" src="https://user-images.githubusercontent.com/27622/122005227-e4176080-cda4-11eb-86cd-90379bd77cd0.png">

The list, however, seems to be based on a PR's "Reviewers" section, not on an "Assignees" section. So PRs assigned by this action don't appear in the list, which is somewhat bothering for me as I have to check a list of PRs filtered by assignees in addition to GitHub's reminders in order to get a full list of PRs waiting for my review.

To address this issue, what do you think of the idea to let `r?` put reviewers to the "Reviewers" section along with the "Assignees" section? @tetsuharuohzeki

**Comment by tetsuharuohzeki** [comment]
@nodaguti 

I think it would be nice to set reviewers to GitHub Pull Requests' "Reviewer" fields.
I also think this behavior change would be controlled by some config (e.g. `set_fields: "assignees", "reviewer", "both")

But I don't have a time to implement it immediately but I can review some pull requests.
I feel this part should be handle to set reviewers.
https://github.com/cats-oss/github-action-auto-assign/blob/master/src/operations.js#L15-L44

**Comment by tetsuharuohzeki** [comment]
>  I also think this behavior change would be controlled by some config (e.g. `set_fields: "assignees", "reviewer", "both")

After some thought, I suspect that we might not need to implement such option.
Feel free whether you implement or not.
