### ISSUE TITLE
PSA: Fading out maintainership

### ISSUE THREAD

**Issue by tetsuharuohzeki** [cats-oss/github-action-auto-assign#248]
Now, I don't have much time to maintain this project, so I'm planning to fade out my maintainership from this project.

I can still review a new PRs for this project but I would not write a new code for this.

**Comment by tetsuharuohzeki** [comment]
@kubosho @nodaguti

I would like to take over that decide to archive this project to you.

NOTE: If you archive this repository, then you would need to consider to "delist" this [from the marketplace](https://github.com/marketplace/actions/auto-assign-a-reviewer-by-commnt-command)

**Comment by kubosho** [comment]
Sorry for the very late reply.

It continues to be used by my team. However, it was not used elsewhere.

So will consider to migrate the this repository to my team's organization account and continue to maintainance.

**Comment by kubosho** [comment]
It has been a long time since our team stopped using this action.

Our team established a workflow without this action, so we have not motivation to maintain this action.

Therefore, I going to archive this repository.
