### ISSUE TITLE
Another approach to support pull requests whose author is a bot

### ISSUE THREAD

**Issue by nodaguti** [cats-oss/github-action-auto-assign#37]
I just came up with another approach to address #33.

How about changing behaviours of `r+` and `r=` commands from assigning a PR to its author to assigning it to a user who most recently uses a command `r?`?

I'm not sure whether this idea is feasible or not since I haven't been digging into it, but what do you think @saneyuki?

**Comment by nodaguti** [comment]
Sorry for annoyance but closing this PR as the strategy doesn't seem to work due to the limitations of GitHub Actions API.

**Comment by saneyuki** [comment]
> How about changing behaviours of r+ and r= commands from assigning a PR to its author to assigning it to a user who most recently uses a command r??

I don't feel that they are best way in both the current behavior and your proposed one.

Ideally, we should automate merging an approved pull request with [bors-ng](https://github.com/bors-ng/bors-ng), [homu](https://github.com/servo/homu), [popuko](https://github.com/voyagegroup/popuko) or others. [I wrote up about them to compare in the past.](http://techlog.voyagegroup.com/entry/2017/02/14/080000)

IMO, with a hat of the creator of  [popuko](https://github.com/voyagegroup/popuko), popuko has some feature duplication with our actions hosted in this GitHub origanization. So I feel it _might_ be better to fork its app and reduce some code for our purpose.

**Comment by nodaguti** [comment]
Using some kind of automerge bot is fairly reasonable approach to this problem. Thank you for your suggestion.
